services:
  neonrain-website-landing-page:
	container_name: neonrain-website-landing-page
	build:
	  context: .
	  dockerfile: Dockerfile
	ports:
	  - "3000:3000"
	environment:
	  - NODE_ENV=production
